### ISSUE TITLE
Bug: NatsError: TIMEOUT

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#489]
### Describe the bug

```
NatsError: TIMEOUT
    at Function.errorForCode (/Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/error.js:101:16)
    at timeout (/Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/util.js:88:35)
    at new RequestOne (/Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/request.js:100:41)
    at NatsConnectionImpl.request (/Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/nats.js:345:23)
    at JetStreamClientImpl.<anonymous> (/Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/jsclient.js:113:39)
    at Generator.next (<anonymous>)
    at /Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/jsclient.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/jsclient.js:18:12)
    at JetStreamClientImpl.publish (/Users/yanivbenhemo/Documents/development/memphis/tutorials/graphql-tutorial/node_modules/nats/lib/nats-base-client/jsclient.js:78:16) {
  code: 'TIMEOUT',
  chainedError: undefined
}
```

### Steps to reproduce

Used code -

```
const memphis = require("memphis-dev");

        (async function () {
            let memphisConnection
        
            try {
                memphisConnection = await memphis.connect({
                    host: 'broker.sandbox.memphis.dev',
                    username: 'test.consumers',
                    connectionToken: 'XrHmszw6rgm8IyOPNNTy'
                });
        
                const producer = await memphisConnection.producer({
                    stationName: 'test-consumers',
                    producerName: 'producer1'
                });
        
                const headers = memphis.headers()
                for(var i = 0; i < 50000; i++) {
                    await producer.produce({
                        message: Buffer.from("Message: Hello world"),
                        headers: headers
                    });
                }
                memphisConnection.close();
            } catch (ex) {
                console.log(ex);
                if (memphisConnection) memphisConnection.close();
            }
        })();
        
```

### Affected services

Broker, SDKs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by idanasulinmemphis** [comment]
Has been fixed on v0.4.1
