### ISSUE TITLE
Bug: Error while creating an HTTP token through React

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#676]
### Describe the bug

```
var axios = require('axios');
        var data = JSON.stringify({
          "username": "*******",
          "connection_token": "*********",
          "token_expiry_in_minutes": 123,
          "refresh_token_expiry_in_minutes": 10000092
        });

        var config = {
          method: 'post',
          url: 'proxy.sandbox.memphis.dev:4444/auth/authenticate',
          headers: {
            'Content-Type': 'application/json'
          },
          data : data
        };
        axios(config)
        .then(function (response) {
          console.log(JSON.stringify(response.data));
        })
        .catch(function (error) {
          console.log(error);
        });
```

Error:

```
AxiosError: Unsupported protocol proxy.sandbox.memphis.dev:
    at dispatchHttpRequest (/private/tmp/http-schemaverse/node_modules/axios/dist/node/axios.cjs:2437:21)
    at new Promise (<anonymous>)
    at http (/private/tmp/http-schemaverse/node_modules/axios/dist/node/axios.cjs:2330:10)
    at Axios.dispatchRequest (/private/tmp/http-schemaverse/node_modules/axios/dist/node/axios.cjs:3260:10)
    at Axios.request (/private/tmp/http-schemaverse/node_modules/axios/dist/node/axios.cjs:3610:33)
    at wrap (/private/tmp/http-schemaverse/node_modules/axios/dist/node/axios.cjs:27:15)
    at Object.<anonymous> (/private/tmp/http-schemaverse/producer.js:17:9)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json'
    },
    method: 'post',
    url: 'proxy.sandbox.memphis.dev:4444/auth/authenticate',
    data: '{"username":"********","connection_token":"********","token_expiry_in_minutes":123,"refresh_token_expiry_in_minutes":10000092}'
  }
}
```

### Steps to reproduce

Create a JWT token through ReactJS code failed.

### Affected services

Broker, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Changing the request URL to this `https://proxy.sandbox.memphis.dev/auth/authenticate` fixed it.
